### ISSUE TITLE
Little doubt about run client.py

### ISSUE THREAD

**Issue by colaresedoardo** [troeger/corba-example#7]
Hello man,
Maybe my question is little simple to you, but  to me it cause my hair fall down. How can I run the client? For example, I'm using debian so when I run in the command-line like: python2 client.py 'Example::echo'. The client can't find object reference. In serve-side is working. But in the client-side isnt.
I'm running the same example that you.
I know is something tha I typing wrong in the command-line. 
error: omniORB.CORBA.BAD_PARAM: CORBA.BAD_PARAM(omniORB.BAD_PARAM_BadSchemeName
Thanks for now,

**Comment by troeger** [comment]
Sounds like a problem with the IOR you provide to the client. Can you check it here:

http://catior.org/cgi-bin/catior
